# Generated by Django 4.2 on 2023-04-27 14:25

from django.db import migrations, models
import django.db.models.deletion
import survivors.models


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=survivors.models.Item.get_default_survivor, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='survivors.survivor'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='survivor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='survivors.survivor'),
        ),
    ]
