# Generated by Django 4.2 on 2023-04-26 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='inventory',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_inventory', to='api.item')),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survivor_inventory', to='api.survivor')),
            ],
        ),
        migrations.AddField(
            model_name='survivor',
            name='items',
            field=models.ManyToManyField(through='api.Inventory', to='api.item'),
        ),
    ]
